# Generated by Django 5.1.15 on 2026-09-18 18:14

import django.db.models.deletion
import integrations.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='zerodha', max_length=30)),
                ('encrypted_access_token', integrations.fields.EncryptedTextField()),
                ('token_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('EQUITY', 'Equity'), ('MUTUAL_FUND', 'Mutual Fund'), ('BOND', 'Bond')], default='EQUITY', max_length=15)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_synced_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('broker_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.brokerconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('broker_connection', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
