# Generated by Django 5.1.15 on 2026-09-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetalRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('PLATINUM', 'Platinum')], max_length=10)),
                ('price_per_gram_999', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['metal', '-fetched_at'], name='rates_metal_metal_a9cf62_idx')],
            },
        ),
    ]
